#!/usr/bin/perl

use strict;
use warnings;
use utf8;

our @Queues = (
	# some definitions here
);

our @CustomFields = (
	# some other definitions here
);

push @Queues, {
	Name => '_Pluginmanager',
	Description => 'Pluginmanager',
};

push @CustomFields, {
	Name => '_pm_OffDate',
	Type => 'DateTime',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_pm_OnDate',
	Type => 'DateTime',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_pm_PlannedOffDate',
	Type => 'DateTime',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_pm_PlannedOnDate',
	Type => 'DateTime',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_pm_PluginName',
	Type => 'Freeform',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_pm_PluginStatus',
	Type => 'Freeform',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_mp_LinkToDownload',
	Type => 'Freeform',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_mp_PluginName',
	Type => 'Freeform',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Name => '_mp_RestartDate',
	Type => 'DateTime',
	MaxValues => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Description =>'',
	ApplyTo => qw / _Pluginmanager  /,
};

push @CustomFields, {
	Description  => 'Plugin config;BigBox',
	UniqueValues  => '0',
	Name  => '_pm_Config',
	Disabled  => '0',
	EntryHint  => 'Egy szöveges mező kitöltése',
	Pattern  => '',
	MaxValues  => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Type  => 'Text',
	ApplyTo => [ qw / _Pluginmanager  /  ] ,
};

push @CustomFields, {
	Pattern  => '',
	MaxValues  => '1',
	LookupType  => 'RT::Queue-RT::Ticket',
	Type  => 'Freeform',
	Description  => 'is config has been changed',
	Disabled  => '0',
	Name  => '_pm_ConfigChanged',
	UniqueValues  => '0',
	EntryHint  => 'Szabad értékmegadás (egy)',
	ApplyTo => [ qw / _Pluginmanager  /  ] ,
};

push @CustomFields, {
	MaxValues => '1',
	Disabled => '0',
	EntryHint => 'Szabad értékmegadás (egy)',
	LookupType => 'RT::Queue-RT::Ticket',
	Pattern => '',
	Name => '_pm_ImmidiateApply',
	Description => '',
	UniqueValues => '0',
	Type => 'Freeform',
	ApplyTo => [ '_Pluginmanager' ] ,
};

push @CustomFields, {
	MaxValues => '1',
	Disabled => '0',
	EntryHint => 'Szabad értékmegadás (egy)',
	LookupType => 'RT::Queue-RT::Ticket',
	Name => '_mp_ImmidiateInstall',
	UniqueValues => '0',
	Description => '',
	Pattern => '',
	Type => 'Freeform',
	ApplyTo => [ '_Pluginmanager' ] ,
};

1;
